FROM python:3.13
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY fast_server ./fast_server
COPY db ./db
COPY tcp_server/tcp_server.py .

CMD ["python", "tcp_server.py"]
